---
title: "ESA Talk"
---

Coming to you live from Sacramento California, it's Datamancy on the Road!

I'm posting this with extreme pre-talk jitters, I will be presenting tomorrow morning in conference room 314 at the Sacramento conference centre. I'm hoping for the best.

If you're reading this after the fact and have come to have another look at my slides, thanks for your interest! I really love what I do and enjoy sharing it just as much, skip to the bottom to get to the slides.

Conference Recap
==================

Environmental Sequencing Workshop
----------------------------------

The ESA 2014 annual meeting has been a whirlwind of wonderful science and people. I was lucky enough to get to sit in on a wonderful workshop lead by Holy Bik, Kelley Thomas, Dorota Porazinska, and Simon Creer on environmental sequencing approaches. It was a blast to hear from such passionate people in such an interesting field.

I went in to the session hoping to learn a little more about the state of the field in order to hopefully answer a irksome problem my supervisor has been grappling with. Our model species (*Splachnum ampullaceum* and *Splachnum pensylvanicum*) are poorly studied genetically so efficient markers don't exist for detecting their spores in the environment. I wanted to tap into the thoughts of people who deal with this kind of problem daily.

I've been inspired to revist the prior work that has been done on developing markers for our species, and perhaps employ some more modern techniques for identifying them. So kudos to the leaders for putting the workshop together.

Talks, Talks, Posters, and More Talks
--------------------------------------

I really enjoyed getting a whirlwind tour of what's going on in ecology research. I focused mostly on catching community ecology and modelling talks. I saw many other young scientists put themselves on display for what must have been an intimidating crowd.

I really enjoyed talks from

[Aaron David](http://asdavid.wordpress.com/) on microbe innoculation sources for new plants. Interesting work in teasing out whether new plant roots gain their fungal endophytes from the parent plant, conspecific neighbours, or the surrounding soil.

[Yue "Max" Li](http://eebweb.arizona.edu/Faculty/chesson/index.htm#Max) from the Chesson lab, looked at coexistence using a long-standing field experiment.

Jiaqi Tan looked at coexistence mechanisms amongst protists. He used a cool strategy to identify dietary strategy amongst the protist, then used dietary preference as a proxy for niche to estimate niche differentiation (amongst other things).

Dan Scholes from Ken Paige's lab in Illinois looking at the genetic basis of plant overcompensation in response to herbivory. I had the pleasure of having dinner with Dan and Ken, fascinating work that reminded me of the Arabidopsis days of my undergrad.

Those are just a few of my highlights, I'd continue but it is exhausting looking for personal websites for young scientists. 


Slides!
=======

